import { NextResponse } from 'next/server'
import { createHash } from 'crypto'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { fetchStockPhoto } from '@/lib/pexels'
import type { ImageStyle } from '@/lib/image-gen'
import { checkRateLimit } from '@/lib/ratelimit'

function encodeBase64url(str: string): string {
  const bytes = new TextEncoder().encode(str)
  let binary = ''
  for (const b of bytes) binary += String.fromCharCode(b)
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const session = await auth()
  if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { id } = await params
  const userId = session.user.id

  const { allowed } = await checkRateLimit(`image-preview:${userId}`, 120, 60)
  if (!allowed) {
    return NextResponse.json({ error: 'Too many requests. Please try again later.' }, { status: 429 })
  }

  const [post, user, prefs] = await Promise.all([
    prisma.post.findFirst({
      where: { id, userId, status: { in: ['pending_approval', 'published'] } },
      select: { generatedContent: true, topic: true, imageStyle: true, linkedInAccountId: true, customImageUrl: true, generatedImageUrl: true, stockPhotoUrl: true },
    }),
    prisma.user.findUnique({
      where: { id: userId },
      select: { plan: true, lifetimeFree: true, name: true },
    }),
    prisma.userPreferences.findUnique({
      where: { userId },
      select: { niche: true, imageStyle: true, brandColor: true, showProfilePicOnCard: true },
    }),
  ])

  if (!post) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  // Serve custom uploaded image directly (user upload takes priority over pre-generated)
  if (post.customImageUrl) {
    // Validate URL is from Vercel Blob to prevent open redirect / SSRF
    try {
      const parsed = new URL(post.customImageUrl)
      if (parsed.protocol !== 'https:' || !parsed.hostname.endsWith('.public.blob.vercel-storage.com')) {
        return NextResponse.json({ error: 'Invalid image URL' }, { status: 400 })
      }
    } catch {
      return NextResponse.json({ error: 'Invalid image URL' }, { status: 400 })
    }
    return NextResponse.redirect(post.customImageUrl)
  }

  // Serve pre-generated image directly (generated by worker at pending_approval creation time)
  if (post.generatedImageUrl) {
    try {
      const parsed = new URL(post.generatedImageUrl)
      if (parsed.protocol !== 'https:' || !parsed.hostname.endsWith('.public.blob.vercel-storage.com')) {
        return NextResponse.json({ error: 'Invalid image URL' }, { status: 400 })
      }
    } catch {
      return NextResponse.json({ error: 'Invalid image URL' }, { status: 400 })
    }
    return NextResponse.redirect(post.generatedImageUrl)
  }

  // AI-generated: serve the Blob URL stored at post time; fall back to quote_card if none stored
  if (post.imageStyle === 'ai_generated') {
    if (post.stockPhotoUrl) {
      try {
        const parsed = new URL(post.stockPhotoUrl)
        if (parsed.protocol !== 'https:' || !parsed.hostname.endsWith('.public.blob.vercel-storage.com')) {
          return NextResponse.json({ error: 'Invalid image URL' }, { status: 400 })
        }
      } catch {
        return NextResponse.json({ error: 'Invalid image URL' }, { status: 400 })
      }
      return NextResponse.redirect(post.stockPhotoUrl)
    }
    // No stored URL — fall through and render a quote_card as fallback
  }

  const account = await prisma.linkedInAccount.findUnique({
    where: { id: post.linkedInAccountId },
    select: { displayName: true, profilePicture: true },
  })

  const style = (post.imageStyle === 'ai_generated' ? 'quote_card' : (post.imageStyle ?? 'quote_card')) as ImageStyle
  const niche = prefs?.niche ?? 'tech professional'

  // Stock photo: use stored URL for consistency (same photo in preview and after publish),
  // or fetch fresh from Pexels and persist the URL for future requests.
  if (style === 'stock_photo') {
    if (post.stockPhotoUrl) {
      return NextResponse.redirect(post.stockPhotoUrl)
    }
    const result = await fetchStockPhoto(post.topic, niche)
    if (result) {
      // Persist URL so every subsequent request (approve, post-publish display) uses the same photo
      prisma.post.update({ where: { id }, data: { stockPhotoUrl: result.url } }).catch(() => {})
      return new Response(new Uint8Array(result.buffer), {
        headers: { 'Content-Type': 'image/jpeg', 'Cache-Control': 'private, max-age=3600' },
      })
    }
    // Pexels failed — fall through to generated card as fallback
  }

  const displayName = account?.displayName ?? user?.name ?? 'Professional'
  const plan = (user?.lifetimeFree ? 'pro' : (user?.plan ?? 'free')) as 'free' | 'pro'
  const brandColor = prefs?.brandColor ?? undefined
  const profilePictureUrl = account?.profilePicture ?? undefined
  const showProfilePic = prefs?.showProfilePicOnCard ?? false
  const fallbackStyle = style === 'stock_photo' ? 'quote_card' : style

  const d = encodeBase64url(JSON.stringify({ style: fallbackStyle, content: post.generatedContent, topic: post.topic, niche, displayName, plan, brandColor, profilePictureUrl, showProfilePic }))
  const secret = process.env.AUTH_SECRET ?? process.env.NEXTAUTH_SECRET
  if (!secret) {
    console.error('[image] AUTH_SECRET is not configured')
    return new Response('Server configuration error', { status: 500 })
  }
  const sig = createHash('sha256').update(d + secret).digest('hex').slice(0, 32)
  const edgeUrl = new URL(`/api/image-render?d=${d}&sig=${sig}`, req.url)
  return NextResponse.redirect(edgeUrl)
}
